name: Keep Streamlit App Warm

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:

jobs:
  keep-warm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer
        run: |
          npm install puppeteer

      - name: Ping Streamlit App
        run: |
          echo "const puppeteer = require('puppeteer');" > ping.js
          echo "puppeteer.launch().then(async browser => {" >> ping.js
          echo "  const page = await browser.newPage();" >> ping.js
          echo "  await page.goto('https://icarus-pvtroi-tool-ekraek9daw6zlbvtrc4hyh.streamlit.app/', {waitUntil: 'networkidle2'});" >> ping.js
          echo "  console.log('Streamlit app loaded');" >> ping.js
          echo "  await browser.close();" >> ping.js
          echo "});" >> ping.js
          node ping.js
